App\Entity\User:
  type: entity
  table: users
  repositoryClass: App\Doctrine\Repository\UserRepository
  id:
    id:
      type: uuid
  fields:
    email:
      type: string
      length: 512
      unique: true
      nullable: false
      column: email
    password:
      type: string
      length: 512
      unique: false
      nullable: false
      column: password